<a href="https://colab.research.google.com/github/rahiakela/hands-on-machine-learning-with-scikit-learn-keras-and-tensorflow/blob/0-math-numpy-pandas-matplotlib-guide/numpy_high_dimensionalarray_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy High Dimensional Array Indexing and Slicing

Let's understand Numpy High Dimensional array indexing that need some mental model so that we could understand it perfectly.

As we know, these are the properties of numpy array:-

* **1D Array**: It is called vector and it has one dimension with shape of (m,).
*  **2D Array**: It is called matrix and it has two dimension with shape of (m, n). It is also called the set of vector.
* **3D Array**: It is called tensor and it has three dimension with shape of (s, m, n). It is also called the set of matrix.

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-1.png?raw=1' width='800'/>

We index dimensions backward in the order, we added them. We can see that:-

1. **"dim0" points to depth of 3d array**
2. **"dim1" points to row of 3d array**
3. **"dim2" points to columns of 3d array**

So in the below image, we have 3d array of size $2 x 3 x 4$ and it is also called the shape of the array.

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-2.png?raw=1' width='800'/>

We can index each item of the 3d array by specifying 3 coordinates.

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-3.png?raw=1' width='800'/>

In [0]:
import numpy as np

In [2]:
arr3d = np.array([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]
    ],
    [
      [13, 14, 15, 16], 
      [17, 18, 19, 20],
      [21, 22, 23, 24]
    ]
])

arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [3]:
arr3d[0, 2, 3]  # first index of 3d array, second row and 3rd column. 

12

In [4]:
arr3d[1, 0, 1]  # second index of 3d array, first row and 2nd column.

14

In [5]:
arr3d[1, 1, 3]  # second index of 3d array, second row and 4th column.

20

In [6]:
arr3d[0, 1, 3]  # first index of 3d array, second row and 4th column.

8

We can refer to slices of the data with partial indics. 

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-4.png?raw=1' width='800'/>

In [8]:
arr3d[0, :, :]   # select all rows and columns of first index

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr3d[1, :, :]   # select all rows and columns of second index

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

Now let's select a specific row of any indics. 

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-5.png?raw=1' width='800'/>

In [11]:
arr3d[:, 1, :]   # select all columns of second row from both indices

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [13]:
arr3d[:, 0, :]  # select all columns of first row from both indices

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

Now let's select a specific column of any indics. 

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-6.png?raw=1' width='800'/>

In [14]:
arr3d[:, :, 2]   # select a specific column(3rd) from both indices

array([[ 3,  7, 11],
       [15, 19, 23]])

In [15]:
arr3d[:, :, 1]   # select a specific column(2nd) from both indices

array([[ 2,  6, 10],
       [14, 18, 22]])

Now let's select a range of row/column from any indics. 

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-7.png?raw=1' width='800'/>

In [17]:
arr3d[0, 1:3, 2:4]   # select a range of row(2nd to 3rd row) and column(3rd to 4th col) from first indices

array([[ 7,  8],
       [11, 12]])

In [18]:
arr3d[0, 0:2, 1:3]   # select a range of row(1st to 2nd row) and column(2nd to 3rd col) from first indices

array([[2, 3],
       [6, 7]])

In [19]:
arr3d[1, 1:3, 2:4]   # select a range of row(2nd to 3rd row) and column(3rd to 4th col) from second indices

array([[19, 20],
       [23, 24]])

In [21]:
arr3d[1, 0:2, 1:3]   # select a range of row(1st to 2nd row) and column(2nd to 3rd col) from second indices

array([[14, 15],
       [18, 19]])

Now let's select a range of column of a row from any indics. 

<img src='https://github.com/rahiakela/img-repo/blob/master/path-ai/tensor-8.png?raw=1' width='800'/>

In [22]:
arr3d[:, 0, 1:3]   # select a range of column(2nd to 3rd col) of first row from both indices

array([[ 2,  3],
       [14, 15]])

In [23]:
arr3d[:, 1, 1:3]   # select a range of column(2nd to 3rd col) of second row from both indices

array([[ 6,  7],
       [18, 19]])

In [24]:
arr3d[0, 0, 1:3]   # select a range of column(2nd to 3rd col) of first row from first indices

array([2, 3])

In [25]:
arr3d[1, 0, 1:3]   # select a range of column(2nd to 3rd col) of first row from second indices

array([14, 15])